name: Build and Deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build-and-deploy]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pages

    steps:
      - name: Checkout landing page
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: devfile/docs
          persist-credentials: false
          path: docs
      
      - name: Build site with antora
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: docs/antora-playbook.yml

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: master
          FOLDER: out
          REPOSITORY_NAME: devfile/devfile.github.io
          CLEAN: true
